language: ruby
script: bundle exec rake test
sudo: false
cache:
  - bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
matrix:
  fast_finish: true
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/chef-11.6/Gemfile
